qbcore-framework/qb-garages

client/main.lua

Fix the Garage name button so it not crash

Fix button

---

SharedConfig.lua

DO NOT PUSH THIS COMMIT WITHOUT TEST THE LASTEST ONE #12

Modify to work with the lastest commit NEED TEST

---

SharedConfig.lua
client/main.lua

adds suggestion https://github.com/qbcore-framework/qb-garages/issues/17

Show/Hide Blips based on config settings

---

SharedConfig.lua
client/main.lua

Reverts qbcore-framework/qb-garages#34

Revert "Show/Hide Blips based on config settings"

---

client/main.lua

This is just a small clean up for notifications/headers/text. This includes a fix for house garages. I removed depot price from house garage header as well.

edit to notifications/headers/text

---

server/main.lua

Fix For Selling Vehicles You Still Owe Money On

Fix Callback For Selling Vehicles

---

client/main.lua
fxmanifest.lua
locales/en.lua
locales/fr.lua
server/main.lua

Locales support and EN+FR locales

Locales support

---

client/main.lua

Fix impound state

---

locales/ge.lua

Created Georgian Language for Garages

Georgian Language

---

README.md
client/main.lua
config.lua
server/main.lua

Bug : In shared garages when you take someone else car and put it back, it goes to the impound. This is resolved
New configuration for shared garages. Set to false by default, you can choose if you want or not the shared garages for Job and Gang

Bug correction + config value

---

client/main.lua
config.lua
fxmanifest.lua
locales/en.lua

Polyzone conversion, nothing else changed. No target as no ped to target

Polyzone conversion

---

client/main.lua

Error when reconnecting at garage range

Avoid error

---

client/main.lua

Server error when a vehicle is taken from the impound

Fix impound error

---

client/main.lua

This fix avoids the zone creation to empty currentGarage variable when login into the garage zone

Fix: currentGarage is nil

---

server/main.lua

House garages doesn't work anymore since security update, this is resolved

Fix: House garages

---

client/main.lua
server/main.lua

This is the fix for /issues/209
Existence of car is now verified
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

Fix : Impound not filled when car disappear

---

server/main.lua

This fixes seized impounded vehicles also being able to be taken out from Depot Lot, 
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

Fix for Taking Seized vehicles also from Depot lot

---

fxmanifest.lua
locales/ar.lua
locales/da.lua
locales/de.lua
locales/en.lua
locales/es.lua
locales/et.lua
locales/fa.lua
locales/fi.lua
locales/fr.lua
locales/ge.lua
locales/it.lua
locales/nl.lua
locales/pt.lua
locales/ro.lua
locales/sk.lua
locales/sv.lua
locales/tr.lua

adding auto switch locale system
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

add auto switch locale system

---

locales/ar.lua
locales/da.lua
locales/de.lua
locales/en.lua
locales/es.lua
locales/et.lua
locales/fa.lua
locales/fi.lua
locales/fr.lua
locales/ge.lua
locales/it.lua
locales/nl.lua
locales/pt.lua
locales/ro.lua
locales/sk.lua
locales/sv.lua
locales/tr.lua

First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]
1 ) No
2 ) Yes
3 ) Yes

[TRANSLATIONS] Remove outdated colors & add [E] to actions

---

locales/de.lua

~g~, ~w~ not working in this message type
no_vehicles keys changed to german
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest) YES
- Does your code fit the style guidelines? [yes/no] YES 
- Does your PR fit the contribution guidelines? [yes/no] YES

[TRANSLATIONS] Dutch

---

client/main.lua
fxmanifest.lua

Existing House Garages Not Showing issue Fix
Existing House Garages not showing since Garages from qb-housing was stored in incorrect variable
fix for issue #273 
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

Fix House Garages not Showing

---

config.lua
server/main.lua

This PR is just add "Config" for shared public garages that make a player can access them car anyware that store in public garages

feat: add shared public garage config

---

server/main.lua

This PR is fairly simple and simply aims to add in the export `getAllGarages`. I personally would like the ability to get all QB-Core garages and their data so I can use it in another resource.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

➕ Add "getAllGarages" export and function

---

server/main.lua

Add export getAllGarages to retrieve garage data from config
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality?
> Yes
- Does your code fit the style guidelines?
> Yes
- Does your PR fit the contribution guidelines?
> Yes

feat: Add export getAllGarages to retrieve garage data from config

---

server/main.lua

Previously by triggering these events you could modify the vehicle of others. This PR makes sure that bad actors are not able to modify the database content of vehicles they do not own.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality?
--> YES
- Does your code fit the style guidelines?
--> YES
- Does your PR fit the contribution guidelines?
--> YES

Fix exploitable net events

---

locales/es.lua

Updated es.lua locale
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [ yes ]
- Does your code fit the style guidelines? [ yes ]
- Does your PR fit the contribution guidelines? [ yes ]

Updated es.lua

---

client/main.lua

Updating qb-garages to fix a bug where you couldn't deposit your vehicle into your house unless you ran ensure qb-garages. Also updated it to use the native QBCore.Shared.Round function.

Fix Issue #366 and use the native QBCore Round function.
